# Generated by Django 4.2.5 on 2024-05-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service_about_high_ar_service_about_high_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='about_high_ar',
        ),
        migrations.RemoveField(
            model_name='service',
            name='about_high_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='about_high_fr',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name_fr',
        ),
        migrations.AlterField(
            model_name='hiring',
            name='permis',
            field=models.BooleanField(default=False, verbose_name='Permis de Conduire'),
        ),
    ]
