# Generated by Django 4.2.5 on 2024-06-02 12:56

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_service_about_high_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name="Nom de l'entreprise")),
                ('image_high', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image_1')),
                ('image_low', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image_2')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Titre')),
                ('about_high', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text a propos')),
                ('about_low', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Page a propos 2')),
            ],
            options={
                'verbose_name': 'about',
                'verbose_name_plural': 'abouts',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='service samll description '),
        ),
        migrations.AlterField(
            model_name='hiring',
            name='permis',
            field=models.BooleanField(default=False, verbose_name='Permis de Conduire '),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='service title'),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=25, verbose_name='Téléphone')),
                ('entreprise', models.CharField(blank=True, max_length=150, null=True, verbose_name="Nom de l'entreprise")),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'quote',
                'verbose_name_plural': 'quotes',
            },
        ),
    ]
