# Generated by Django 4.2.5 on 2024-06-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_company_alter_contactform_phone_companyitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=50, verbose_name='email'),
        ),
    ]
