# Generated by Django 4.2.5 on 2024-06-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_contactform_service_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image_breadcrumb',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image_1'),
        ),
    ]
