# Generated by Django 4.2.5 on 2024-06-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_about_brochure'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_breadcrumb',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='breadcrumb image'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image_breadcrumb',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='breadcrumb image'),
        ),
    ]
