# Generated by Django 4.2.5 on 2024-07-11 08:35

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_service_image_breadcrumb_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'contact', 'verbose_name_plural': 'contact'},
        ),
        migrations.AddField(
            model_name='service',
            name='about_high_ar',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text service'),
        ),
        migrations.AddField(
            model_name='service',
            name='about_high_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text service'),
        ),
        migrations.AddField(
            model_name='service',
            name='about_high_fr',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text service'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='service title'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='service title'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_fr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='service title'),
        ),
    ]
