# Generated by Django 4.2.5 on 2024-07-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_contact_options_service_about_high_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.CharField(default='one', max_length=500, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
