# Generated by Django 4.2.5 on 2024-07-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_company_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='URL'),
        ),
    ]
