# Generated by Django 4.2.5 on 2024-07-11 10:43

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='description_ar',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description du service'),
        ),
        migrations.AddField(
            model_name='solution',
            name='description_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description du service'),
        ),
        migrations.AddField(
            model_name='solution',
            name='description_fr',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description du service'),
        ),
        migrations.AddField(
            model_name='solution',
            name='name_ar',
            field=models.CharField(max_length=50, null=True, verbose_name='Nom de la solution'),
        ),
        migrations.AddField(
            model_name='solution',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Nom de la solution'),
        ),
        migrations.AddField(
            model_name='solution',
            name='name_fr',
            field=models.CharField(max_length=50, null=True, verbose_name='Nom de la solution'),
        ),
        migrations.AddField(
            model_name='solution',
            name='text_ar',
            field=models.TextField(blank=True, null=True, verbose_name='petit texte'),
        ),
        migrations.AddField(
            model_name='solution',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='petit texte'),
        ),
        migrations.AddField(
            model_name='solution',
            name='text_fr',
            field=models.TextField(blank=True, null=True, verbose_name='petit texte'),
        ),
        migrations.AddField(
            model_name='solution',
            name='title_ar',
            field=models.CharField(max_length=70, null=True, verbose_name='Grand titre de la solution'),
        ),
        migrations.AddField(
            model_name='solution',
            name='title_en',
            field=models.CharField(max_length=70, null=True, verbose_name='Grand titre de la solution'),
        ),
        migrations.AddField(
            model_name='solution',
            name='title_fr',
            field=models.CharField(max_length=70, null=True, verbose_name='Grand titre de la solution'),
        ),
    ]
