# Generated by Django 4.2.5 on 2024-07-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_solution_description_ar_solution_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Grand titre de la solution'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='title_ar',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Grand titre de la solution'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='title_en',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Grand titre de la solution'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='title_fr',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Grand titre de la solution'),
        ),
    ]
