# Generated by Django 4.2.5 on 2024-07-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_solution_title_alter_solution_title_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activer la solution'),
        ),
    ]
