# Generated by Django 4.2.5 on 2024-07-14 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_solution_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service', verbose_name='service'),
        ),
    ]
