# Generated by Django 4.2.5 on 2024-05-30 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_business_mini_about_ar_business_mini_about_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='about_ar',
        ),
        migrations.RemoveField(
            model_name='business',
            name='about_en',
        ),
        migrations.RemoveField(
            model_name='business',
            name='about_fr',
        ),
        migrations.RemoveField(
            model_name='business',
            name='address_ar',
        ),
        migrations.RemoveField(
            model_name='business',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='business',
            name='address_fr',
        ),
        migrations.RemoveField(
            model_name='business',
            name='meta_description_ar',
        ),
        migrations.RemoveField(
            model_name='business',
            name='meta_description_en',
        ),
        migrations.RemoveField(
            model_name='business',
            name='meta_description_fr',
        ),
        migrations.RemoveField(
            model_name='business',
            name='meta_title_ar',
        ),
        migrations.RemoveField(
            model_name='business',
            name='meta_title_en',
        ),
        migrations.RemoveField(
            model_name='business',
            name='meta_title_fr',
        ),
        migrations.RemoveField(
            model_name='business',
            name='mini_about_ar',
        ),
        migrations.RemoveField(
            model_name='business',
            name='mini_about_en',
        ),
        migrations.RemoveField(
            model_name='business',
            name='mini_about_fr',
        ),
        migrations.RemoveField(
            model_name='business',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='business',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='business',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='business',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='business',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='business',
            name='title_fr',
        ),
    ]
