# Generated by Django 4.2.5 on 2024-06-02 09:48

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_business_buttons_color_business_buttons_text_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='buttons_color',
            field=colorfield.fields.ColorField(blank=True, default='#011627', image_field=None, max_length=25, null=True, samples=None, verbose_name='Button color'),
        ),
        migrations.AlterField(
            model_name='business',
            name='buttons_text_color',
            field=colorfield.fields.ColorField(blank=True, default='#ffffff', image_field=None, max_length=25, null=True, samples=None, verbose_name='Button text color'),
        ),
        migrations.AlterField(
            model_name='business',
            name='footer_color',
            field=colorfield.fields.ColorField(blank=True, default='#011627', image_field=None, max_length=25, null=True, samples=None, verbose_name='Footer color'),
        ),
        migrations.AlterField(
            model_name='business',
            name='footer_text_color',
            field=colorfield.fields.ColorField(blank=True, default='#ffffff', image_field=None, max_length=25, null=True, samples=None, verbose_name='Footer text color'),
        ),
        migrations.AlterField(
            model_name='business',
            name='header_color',
            field=colorfield.fields.ColorField(blank=True, default='#011627', image_field=None, max_length=25, null=True, samples=None, verbose_name='Navigation bar color'),
        ),
        migrations.AlterField(
            model_name='business',
            name='header_text_color',
            field=colorfield.fields.ColorField(blank=True, default='#ffffff', image_field=None, max_length=25, null=True, samples=None, verbose_name='Navigation bar text color'),
        ),
        migrations.AlterField(
            model_name='business',
            name='theme_color',
            field=colorfield.fields.ColorField(blank=True, default='#011627', image_field=None, max_length=25, null=True, samples=None, verbose_name='Theme color'),
        ),
        migrations.AlterField(
            model_name='business',
            name='theme_text_color',
            field=colorfield.fields.ColorField(blank=True, default='#ffffff', image_field=None, max_length=25, null=True, samples=None, verbose_name='Text color'),
        ),
    ]
