# Generated by Django 4.2.5 on 2024-06-02 09:58

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_alter_business_buttons_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='banner_color',
            field=colorfield.fields.ColorField(blank=True, default='#ffffff', image_field=None, max_length=25, null=True, samples=None, verbose_name='Banner background '),
        ),
        migrations.AddField(
            model_name='business',
            name='banner_text_color',
            field=colorfield.fields.ColorField(blank=True, default='#ffffff', image_field=None, max_length=25, null=True, samples=None, verbose_name='Banner text color'),
        ),
    ]
