# Generated by Django 4.2.5 on 2024-06-02 10:11

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_business_banner_color_business_banner_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='buttons_hover_color',
            field=colorfield.fields.ColorField(blank=True, default='#011627', image_field=None, max_length=25, null=True, samples=None, verbose_name='Button hover color'),
        ),
    ]
