# Generated by Django 4.2.5 on 2024-06-02 10:57

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_business_buttons_hover_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='banner_maintext_color',
            field=colorfield.fields.ColorField(blank=True, default='#ffffff', image_field=None, max_length=25, null=True, samples=None, verbose_name='Banner main text color'),
        ),
        migrations.AddField(
            model_name='business',
            name='header_hover_color',
            field=colorfield.fields.ColorField(blank=True, default='#011627', image_field=None, max_length=25, null=True, samples=None, verbose_name='Navigation hover color'),
        ),
    ]
