# Generated by Django 4.2.5 on 2024-06-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_business_banner_maintext_color_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='service',
        ),
        migrations.DeleteModel(
            name='Hiring',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='service',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
